const fs = require("fs");
const os = require("os");
const path = require("path");
const { session } = require("electron");

const DOUYIN_URLS = [
  "https://www.douyin.com",
  "https://douyin.com",
  "https://v.douyin.com",
  "https://iesdouyin.com",
];

function toNetscapeExpiry(expirationDate) {
  if (!expirationDate || expirationDate <= 0) {
    return "0";
  }
  return String(Math.floor(expirationDate));
}

function cookieToNetscapeLine(cookie) {
  const domain = cookie.domain || "";
  if (!cookie.name) {
    return null;
  }
  const includeSubdomains = domain.startsWith(".") ? "TRUE" : "FALSE";
  const cookiePath = cookie.path || "/";
  const secure = cookie.secure ? "TRUE" : "FALSE";
  const expiry = toNetscapeExpiry(cookie.expirationDate);
  return `${domain}\t${includeSubdomains}\t${cookiePath}\t${secure}\t${expiry}\t${cookie.name}\t${cookie.value}`;
}

function hasDouyinLoginCookies(cookies) {
  const names = new Set((cookies || []).map((item) => item.name));
  return names.has("sessionid") || names.has("sessionid_ss");
}

async function collectDouyinCookies(ses = session.defaultSession) {
  const seen = new Set();
  const all = [];

  for (const url of DOUYIN_URLS) {
    const batch = await ses.cookies.get({ url });
    for (const cookie of batch) {
      const key = `${cookie.domain}|${cookie.name}|${cookie.path}`;
      if (seen.has(key)) {
        continue;
      }
      seen.add(key);
      all.push(cookie);
    }
  }

  const broad = await ses.cookies.get({});
  for (const cookie of broad) {
    const host = cookie.domain || "";
    if (!/douyin|iesdouyin|amemv|snssdk|byteoversea/i.test(host)) {
      continue;
    }
    const key = `${cookie.domain}|${cookie.name}|${cookie.path}`;
    if (seen.has(key)) {
      continue;
    }
    seen.add(key);
    all.push(cookie);
  }

  return all;
}

async function exportDouyinCookiesToFile(ses = session.defaultSession) {
  const cookies = await collectDouyinCookies(ses);
  const dir = path.join(os.tmpdir(), "jyconvert");
  fs.mkdirSync(dir, { recursive: true });
  const filePath = path.join(dir, `douyin-cookies-${Date.now()}.txt`);
  const lines = [
    "# Netscape HTTP Cookie File",
    "# Generated by jyconvert",
    ...cookies.map(cookieToNetscapeLine).filter(Boolean),
  ];
  fs.writeFileSync(filePath, `${lines.join("\n")}\n`, "utf8");
  return { filePath, count: cookies.length, cookies };
}

module.exports = {
  collectDouyinCookies,
  exportDouyinCookiesToFile,
  hasDouyinLoginCookies,
};
